
CUHK_ABBR: dict[str, str] = {
    # ---- Colleges (the 9 constituent colleges) ----
    "CC": "Chung Chi College",
    "NA": "New Asia College",
    "UC": "United College",
    "SC": "Shaw College",
    "MC": "Morningside College",
    "SHHO": "S.H. Ho College",
    "CWC": "C.W. Chu College",
    "WYS": "Wu Yee Sun College",
    "LWS": "Lee Woo Sing College",
    # ---- Faculties ----
    "ART": "Faculty of Arts",
    "BA": "Faculty of Business Administration",
    "EDU": "Faculty of Education",
    "ENG": "Faculty of Engineering",
    "LAW": "Faculty of Law",
    "MED": "Faculty of Medicine",
    "SCI": "Faculty of Science",
    "SSC": "Faculty of Social Science",
    "GS": "Graduate School",
    # ---- Common academic terms ----
    "sem": "semester",
    "term": "term/semester",
    "AY": "Academic Year",
    "GPA": "Grade Point Average",
    "CGPA": "Cumulative Grade Point Average",
    "GE": "General Education",
    "GEF": "General Education Foundation",
    "ULE": "University Language Enhancement",
    "credit": "credit unit",
    "cr": "credit unit",
    "UG": "Undergraduate",
    "PG": "Postgraduate",
    "TPg": "Taught Postgraduate",
    "RPg": "Research Postgraduate",
    "MPhil": "Master of Philosophy",
    "PhD": "Doctor of Philosophy",
    "exch": "exchange (student exchange programme)",
    "minor": "minor programme",
    "major": "major programme",
    "elec": "elective course",
    "req": "required/core course",
    "prereq": "prerequisite",
    # ---- Registration / admin ----
    "CUSIS": "Chinese University Student Information System",
    "reg": "registration",
    "add/drop": "course add/drop period",
    "WD": "course withdrawal",
    "RES": "Result/Examination Result",
    "transcript": "academic transcript",
    "SID": "Student ID",
    "OnePass": "CUHK OnePass account",
    "OneCard": "CUHK Student/Staff Card",
    "RO": "Registry / Registration and Examinations Section",
    "OAL": "Office of Academic Links (exchange/study abroad)",
    "OSA": "Office of Student Affairs",
    "CLEAR": "Centre for Learning Enhancement And Research",
    "ILC": "Independent Learning Centre",
    # ---- Campus locations ----
    "MMW": "Mong Man Wai Building",
    "ERB": "Esther Lee Building",
    "YIA": "Yasumoto International Academic Park",
    "LSK": "Lee Shau Kee Building",
    "SHB": "Ho Sin-Hang Engineering Building",
    "SC_Sci": "Science Centre",
    "UL": "University Library",
    "ELB": "Elisabeth Luce Moore Library",
    "MC_Lib": "Lee Quo Wei Law Library",
    "Univ": "University Station (MTR)",
    "Pier": "University Pier",
    # ---- Student life ----
    "SU": "Student Union",
    "Hall": "Student Hostel/Residence",
    "Ori": "Orientation (O-Camp)",
    "OCamp": "Orientation Camp",
    "PE": "Physical Education",
    "CSC": "Career Services Centre / Careers",
    "OWO": "Office of Wellbeing / Wellness",
    "CWS": "Counselling and Wellness",
    # ---- University Administrative Offices & Units ----
    "OAL": "Office of Academic Links",
    "OSA": "Office of Student Affairs",
    "OUS": "Office of University Safety",
    "ITSC": "Information Technology Services Centre",
    "ORKTS": "Office of Research and Knowledge Transfer Services",
    "OAA": "Office of Academic Affairs",
    "OGA": "Office of General Administration",
    "FO": "Finance Office",
    "PRO": "Personnel / Human Resources Office",
    "CPRO": "Communications and Public Relations Office",
    "RO": "Registry (Registration & Examinations Section)",
    "GSO": "Graduate School Office",
    "OAFA": "Office of Admissions and Financial Aid",
    "SFAO": "Student Financial Aid Office",
    "CLEAR": "Centre for Learning Enhancement And Research",
    "ELTU": "English Language Teaching Unit",
    "CLC": "Chinese Language Centre",
    "ILC": "Independent Learning Centre",
    "CSC": "Career Planning and Development Centre / Careers",
    "WCC": "Wellness and Counselling Centre",
    "USC": "University Sports Centre",
    "UHS": "University Health Service",
    "EPO": "Estates Office / Estates Management Office",
    "CSE_off": "Campus Services / Catering & Amenities",
    # ---- Academic Department Course Codes (subject prefixes) ----
    "ANTH": "Anthropology",
    "ARCH": "Architecture",
    "BCHE": "Biochemistry",
    "BIOL": "Biology",
    "BMEG": "Biomedical Engineering",
    "CENG": "Chemical Engineering / Chemistry",
    "CHEM": "Chemistry",
    "CHLT": "Chinese Language and Literature",
    "CSCI": "Computer Science",
    "ECON": "Economics",
    "EEEN": "Electronic Engineering",
    "ELED": "Education / English Language Education",
    "ENGE": "English",
    "ENGG": "Engineering (Faculty common)",
    "ESTR": "Engineering Stream (common core)",
    "FINA": "Finance / Fine Arts (context-dependent!)",
    "GEUC": "General Education (United College)",
    "GECC": "General Education (Chung Chi College)",
    "GENA": "General Education (New Asia College)",
    "GESH": "General Education (Shaw College)",
    "GPAD": "Government and Public Administration",
    "HIST": "History",
    "JLPT": "Japanese Studies (course context)",
    "JASP": "Japanese Studies",
    "LAWS": "Law",
    "MATH": "Mathematics",
    "MGNT": "Management",
    "MKTG": "Marketing",
    "MEDU": "Medicine (general)",
    "NURS": "Nursing",
    "PHAR": "Pharmacy",
    "PHIL": "Philosophy",
    "PHYS": "Physics",
    "PSYC": "Psychology",
    "RMSC": "Risk Management Science",
    "SEEM": "Systems Engineering and Engineering Management",
    "SOCI": "Sociology",
    "SOWK": "Social Work",
    "STAT": "Statistics",
    "TRAN": "Translation",
    "UGEA": "University GE - Foundation: In Dialogue with Humanity",
    "UGEB": "University GE - Foundation: In Dialogue with Nature",
    "UGEC": "University General Education (Area C)",
    "UGED": "University General Education (Area D)",
    # ---- Misc ----
    "HK": "Hong Kong",
    "MTR": "Mass Transit Railway",
    "TBA": "To Be Announced",
    "TBC": "To Be Confirmed",
    "FYP": "Final Year Project",
    "ID": "Identity/Identification",
}
